name: king-norm-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - coverage
  - matplotlib
  - mkdocs
  - mkdocs-material
  - mkdocstrings-python
  - mpmath
  - mypy
  - numpy
  - pandas
  - pip
  - pyperf
  - pymdown-extensions
  - pytest
  - pytest-cov
  - python-build
  - ruff
  - setuptools
  - scipy
  - tqdm
  - wheel
