site_name: WIP TODO
site_description: WIP TODO
nav:
  - Home: index.md

theme:
  name: material
  features:
    - navigation.sections # Collapsible sidebars
    - search.suggest      # Smart search auto-complete
  palette:
    # Set default to dark mode for scientific tools
    scheme: slate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [.] # Project modules live at repository root
          options:
            docstring_style: numpy
            show_source: true # Adds a "View Source" button to the docs
            show_root_heading: true
            show_root_full_path: false

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true # Critical for parsing MathJax correctly

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
